### PR TITLE
try clause for archive function (dxpy)

### LINKED ISSUE #15: Error when archiving record file (DNANexus)
```
2023-01-01 10:55:20,592:main-log:main:INFO:::ARCHIVING: record-GBFb9Z84X7kx1jpY4xgKBbJP
Error while retrieving session configuration: AttributeError: 'NoneType'
object has no attribute 'pid'
Using env variable HTTPS_PROXY=https://proxy.net.addenbrookes.nhs.uk:8080/ as proxy
Traceback (most recent call last):
  File "main.py", line 1210, in <module>
    archiving_function(archive_pickle, today)
  File "main.py", line 1036, in archiving_function
    dx.DXFile(file_id, project=proj_id).archive()
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/dxfile.py", line 211, in __init__
    DXDataObject.__init__(self, dxid=dxid, project=project)
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/__init__.py", line 209, in __init__
    self.set_ids(dxid, project)
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/dxfile.py", line 369, in set_ids
    DXDataObject.set_ids(self, dxid, project)
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/__init__.py", line 292, in set_ids
    verify_string_dxid(dxid, self._class)
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/__init__.py", line 53, in verify_string_dxid
    raise DXError('Invalid ID of class %s: %r' % (str_expected_classes, dxid))
dxpy.exceptions.DXError: Invalid ID of class file: 'record-GBFb9Z84X7kx1jpY4xgKBbJP'
Exception ignored in: <function DXFile.__del__ at 0x7f4f009804c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/dxfile.py", line 297, in __del__
    if not hasattr(self, '_write_buf'):
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/__init__.py", line 102, in __getattr__
    self.describe()
  File "/usr/local/lib/python3.8/site-packages/dxpy/bindings/__init__.py", line 356, in describe
    raise DXError('This {handler} handler has not been initialized with a {_class} ID and cannot be described'.format(
dxpy.exceptions.DXError: This DXFile handler has not been initialized with a file ID and cannot be described
```

### PR DESCRIPTION
**Pull request by JasonLing95**
# Update
- try clause for .archive function
- remove email function (SENDER, RECEIVER, PORT, SMTP) as it is getting phased out
- some function renaming
- renaming `notify.py` to `slack.py` and `Slack` class to `SlackClass`

# Fix
#15

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/16)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/16)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @JasonLing95)

___
*[`main.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/16#-NKrxXplDw9Yt1mAze6Q:-NKrxXplDw9Yt1mAze6R:b-yg6kx9) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/cf3043ce49cbde48184890999908b5bdf5b7f347/main.py#L27)):*
> ```Python
> 
> from helper import get_logger
> from slack import SlackClass
> ```

any reason for the renaming? `Slack` seems fine to me



_Code quote:_
```Python
SlackClass
```
___
*[`main.py` line 976 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/16#-NKrxm47B-i--osAVcXV:-NKrxm47B-i--osAVcXW:b-lj1o04) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/cf3043ce49cbde48184890999908b5bdf5b7f347/main.py#L976)):*
> ```Python
>                             try:
>                                 dx.DXFile(file_id, project=proj_id).archive()
>                             except Exception as er:
> ```

should we be alerted with a summary of files that couldn't be archived? you could explicitly check and skip `record-` files since these aren't real files and can't be archived



_Code quote:_
```Python
 except Exception as er:
```
___
*[`slack.py` line 153 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/16#-NKry28H7wcyIkACcUQG:-NKry28IBT32Da3tbvBT:b-aflr8e) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/cf3043ce49cbde48184890999908b5bdf5b7f347/slack.py#L153)):*
> ```Python
>                     'https://slack.com/api/chat.postMessage', {
>                         'token': self.token,
>                         'channel': f'U01D8NU3DJ5',
> ```

what is this?



_Code quote:_
```Python
'U01D8NU3DJ5
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/16)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/16#-NKrxXplDw9Yt1mAze6Q:-NKryHSd51IuiyfULMPZ:b-4bgevg) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/cf3043ce49cbde48184890999908b5bdf5b7f347/main.py#L27)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

any reason for the renaming? `Slack` seems fine to me
</blockquote></details>

no reason but SlackClass is more defined than Slack
___
*[`main.py` line 976 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/16#-NKrxm47B-i--osAVcXV:-NKryOF88_qm84vE9G2O:bs3nlit) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/cf3043ce49cbde48184890999908b5bdf5b7f347/main.py#L976)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should we be alerted with a summary of files that couldn't be archived? you could explicitly check and skip `record-` files since these aren't real files and can't be archived
</blockquote></details>

that's the problem the last time when it called archive() on record file and caused the script to stop. The above find_data_objects with filter classname='files' should fix it and return mostly files. 

I don't think we need to be alerted on file-id with failed archive because the only reason I can think of if a file can't be archived is that it is in half-closing status - which I don't think will happen in this case as the function should mostly return 'old enough' files which are 6 months or 3 months old. So it's unlikely the archive will fail on files-id
___
*[`slack.py` line 153 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/16#-NKry28H7wcyIkACcUQG:-NKs-oFuChcfP95MHFkH:b-iuncpv) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/cf3043ce49cbde48184890999908b5bdf5b7f347/slack.py#L153)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is this?
</blockquote></details>

removed. You've found out my secret test channel

**Review by jethror1 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/16)* status: 3 of 4 files reviewed, all discussions resolved

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/16)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/16#-:-NKs2kNs32hI-BRkfRPZ:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
