### PR TITLE
Slack class, exclude ENV

### LINKED ISSUE #9: Reduce request response size in `dx.search.find_data_objects()` calls
When finding data objects with `describe=True` on large numbers of files, a lot of data is returned in the response. This can be filtered down by specifying fields to return to only get what is needed, this should speed up the querying as less data has to be returned from the API server.

Example call to change: https://github.com/eastgenomics/automated-archiving/blob/7065480c9d4ba4e87b2cad40df7441ba3535abbb/main.py#L783

Docs for the `describe` method: http://autodoc.dnanexus.com/bindings/python/current/dxpy_bindings.html?highlight=describe#dxpy.bindings.DXDataObject.describe

Working example to only return the `class` in the `describe` dictionary (`id`) is always returned:
```
>>> list(
dx.search.find_data_objects(
    classname='file',
    project='project-FkyzZkQ4pPv6pg2f5GXvvzp4',
    describe={'fields':{'class': True}})
)

[
  {'project': 'project-FkyzZkQ4pPv6pg2f5GXvvzp4', 'id': 'file-FkyzbGj4pPvGbB75KfXKxXbY', 'describe': {'id': 'file-FkyzbGj4pPvGbB75KfXKxXbY', 'class': 'file'}},
  {'project': 'project-FkyzZkQ4pPv6pg2f5GXvvzp4', 'id': 'file-FkyzbGj4pPv7qVPJ0FgFYYZ5', 'describe': {'id': 'file-FkyzbGj4pPv7qVPJ0FgFYYZ5', 'class': 'file'}},
  {'project': 'project-FkyzZkQ4pPv6pg2f5GXvvzp4', 'id': 'file-FkyzbGj4pPv2YYVQ1k9ZpY1B', 'describe': {'id': 'file-FkyzbGj4pPv2YYVQ1k9ZpY1B', 'class': 'file'}}
]
```

### PR DESCRIPTION
**Pull request by JasonLing95**
## Changes
1. Slack class `notify.py`
2. update env.example
3. added AUTOMATED_REGEX_EXCLUDE to be parsed as a list of regex filename to exclude
4. added ARCHIVE_DEBUG, if TRUE, script still run without running actionable code (`archive`). Easy for testing later on
5. added describe field in most `find_data_object` . Fix #9

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/10)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/10)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`main.py` line 458 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67CBASETFAhZxJNZjw:-N67CBASETFAhZxJNZjx:b-ki3sgl) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/main.py#L458)):*
> ```Python
>             logger.info(f'ARCHIVING EXCLUDE staging52: {dir_path}')
> 
>             if DEBUG == 'FALSE':
> ```

why is debug being stored as a FALSE string instead of a boolean `True` / `False`? If it was just False then this would just be  `if DEBUG:`
___
*[`main.py` line 991 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67DEO41TDm3YKRBP0G:-N67DEO41TDm3YKRBP0H:b-9xipem) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/main.py#L991)):*
> ```Python
>                     big_exclude_list = set()
> 
>                     for word in AUTOMATED_REGEX_EXCLUDE:
> ```

could you add a comment or two for why this is being done, I think I understand it all but for future us to remember
___
*[`notify.py` line 18 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67Ctr76cOdZorufPk7:-N67Ctr76cOdZorufPk8:b-5swwle) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/notify.py#L18)):*
> ```Python
> 
> 
> class Slack():
> ```

has any of the messaging changed or just refactored into a separate script? also have you any screenshots of the notifications to know they work?
___
*[`README.md` line 54 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67Cn6eE_J2z_vTToNd:-N67Cn6eE_J2z_vTToNe:b-ftejcv) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/README.md#L54)):*
> ```Markdown
> - `TAR_MONTH`: Period of tar.gz being inactive to be considered 'old enough' (only used by `get_old_tar_and_notify` function)
> - `ARCHIVE_MODIFIED_MONTH`: During archiving_function, if file if modified in the last `ARCHIVE_MODIFIED_MONTH` month, we skip archiving it
> - `DEBUG`: TRUE / FALSE (str) comment out actionable codes (e.g. tag file, remove file tag, archive) if TRUE
> ```

as above, should this be `True` / `False`?

**Review by jethror1 — COMMENTED** [review]
can you add the regex to the readme please

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-:-N67EiNn346ceTbolxfY:b-8ajie3)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @JasonLing95 and @jethror1)

**Review by JasonLing95 — COMMENTED** [review]
added

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-:-N68AL1G8CsDcKxJP8Zu:b-7tfmjp)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`main.py` line 458 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67CBASETFAhZxJNZjw:-N68ANaB5_qrrwTcK9M6:b-od1xnw) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/main.py#L458)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why is debug being stored as a FALSE string instead of a boolean `True` / `False`? If it was just False then this would just be  `if DEBUG:`
</blockquote></details>

Can't import Boolean variable so it's either if DEBUG exist or if DEBUG == 'certain string'. 
___
*[`main.py` line 991 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67DEO41TDm3YKRBP0G:-N68BYlH1MTByz5jn3bV:b-p1i752) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/main.py#L991)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you add a comment or two for why this is being done, I think I understand it all but for future us to remember
</blockquote></details>

added comment
___
*[`notify.py` line 18 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67Ctr76cOdZorufPk7:-N68BamG42C8hhOgVWKK:brax6n7) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/notify.py#L18)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

has any of the messaging changed or just refactored into a separate script? also have you any screenshots of the notifications to know they work?
</blockquote></details>

nothing has changed, just moved to a new script `notify.py` and put into a class `Slack`. Only addition is that now Slack class take in a self.debug, if true, it sends message to egg-test instead of whichever channel the user specify

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/10)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 54 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67Cn6eE_J2z_vTToNd:-N68Br170-Uyn1jvETgr:b-qnef5c) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/README.md#L54)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

as above, should this be `True` / `False`?
</blockquote></details>

string version of TRUE / FALSE (capitalized)

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/10)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 458 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67CBASETFAhZxJNZjw:-N68E8daE4FVEn1oe-CW:ba7kyqx) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/main.py#L458)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

Can't import Boolean variable so it's either if DEBUG exist or if DEBUG == 'certain string'. 
</blockquote></details>

changed to os.environ.get('ARCHIVE_DEBUG', False). Thus if env exist in config, it translate to True
___
*[`README.md` line 54 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/10#-N67Cn6eE_J2z_vTToNd:-N68EJF8D4iAVDcipxDM:b-75yicj) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/87f97a0329fcadbe9bba8c79f81f5590a17bc926/README.md#L54)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

string version of TRUE / FALSE (capitalized)
</blockquote></details>

changed in latest commit to Boolean

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
