### PR TITLE
IN-513: Add WES CEN criteria

### PR DESCRIPTION
**Pull request by JasonLing95**
# Change
- add new env `AUTOMATED_CEN_WES_MONTH` to determine Nth month where WES/CEN 002 project fits the criteria for archiving
- add WES/CEN logic when finding projects that are "old enough" for archiving

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/39)

### CODE REVIEW

**Review by corbin-chris — CHANGES_REQUESTED** [review]
Could you please add the point about CEN WES acting differently from other 002 projects in the README?
I'd also appreciate a more general opening sentence in the 'What does the script do' section of the README. Something along the lines of 'this script automatically lists DNAnexus projects in need of archiving, if the projects exceed a pre-determined age which varies by project type. On the 1th and 15th of the month, the script carries archiving out on these files'. It doesn't have to be exactly like that but right now it launches right into the details before it covers the 'why', which can be a bit confusing.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-:-NuyRh5u4zx76ZjWtZYW:baimuya)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`bin/environment.py` line 121 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-NuyPOSD4fSVwaqI--R3:-NuyPOSD4fSVwaqI--R4:bgys7o9) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/d8a8e56a16b449fc92f234e0e0cb8c6a9f305a42/bin/environment.py#L121)):*
> ```Python
>     def _print_variables(self):
>         """
>         Print all the variables
> ```

Maybe clarify that it's all variables required for troubleshooting/tracking progress (as you leave out the tokens, for example)
___
*[`bin/find.py` line 50 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-NuyQ04_EhRNXzVX7YiA:-NuyQ04_EhRNXzVX7YiB:bvr91w1) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/d8a8e56a16b449fc92f234e0e0cb8c6a9f305a42/bin/find.py#L50)):*
> ```Python
>         - that are old enough
>         - that are not fully archived
>         - that have `archive` tag
> ```

Add a note to the docstring to say that you apply different logic for 002 projects, depending on whether the project is CEN WES or not

**Review by JasonLing95 — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-:-Nv1nnSuAPDuuhGJ-b-o:bb7f2mf)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`bin/environment.py` line 121 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-NuyPOSD4fSVwaqI--R3:-Nv1oj_G0GfsPaKygVRT:bcqtlii) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/d8a8e56a16b449fc92f234e0e0cb8c6a9f305a42/bin/environment.py#L121)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Maybe clarify that it's all variables required for troubleshooting/tracking progress (as you leave out the tokens, for example)
</blockquote></details>

added "except for sensitive ones"
___
*[`bin/find.py` line 50 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-NuyQ04_EhRNXzVX7YiA:-Nv1ozdpD1wpPoEyXoku:bb7f2mf) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/d8a8e56a16b449fc92f234e0e0cb8c6a9f305a42/bin/find.py#L50)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Add a note to the docstring to say that you apply different logic for 002 projects, depending on whether the project is CEN WES or not
</blockquote></details>

done

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/39)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`README.md` line 7 at r2](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-Nv6_2pp5zDrtt_FQ5Li:-Nv6_2pp5zDrtt_FQ5Lj:bkryv7r) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/4945d781a87bbc86ab5583b7021c033d4db80d16/README.md#L7)):*
> ```Markdown
> ## Summary
> This script automates archiving projects and directories on DNAnexus platform - runs on the 1st and 15th of each month. 
> It finds 002 / 003 projects, directories in 001_stagingarea52 and directories in precision brain projects which fit the pre-determined criteria for archiving, send notitification to Slack and perform archiving in the next run.
> ```

This text has become italicised, you might have put some markdown character in here by accident?
Typo: 'notitification' instead of 'notification'

**Review by corbin-chris — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/39)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

___
*[`README.md` line 7 at r2](https://reviewable.io/reviews/eastgenomics/automated-archiving/39#-Nv6_2pp5zDrtt_FQ5Li:-Nv6aiTT1s1xjndaFxBM:b-xgmfh4) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/4945d781a87bbc86ab5583b7021c033d4db80d16/README.md#L7)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

updated the typo - seems to be normal font on GitHub
</blockquote></details>

Done yeah looks like a Reviewable thing

**Pull request merged**
