### PR TITLE
add countdown and archived notification

### PR DESCRIPTION
**Pull request by JasonLing95**
PR added two functions:
1. countdown notification if run date is not 1st or 15th of the month
2. archived notification on what files have been archived after the archiving_function

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 134 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-Mwf7UYs0flLPPbHNEp7:-Mwf7UYs0flLPPbHNEp8:bpv93f4) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L134)):*
> ```Python
>     # just in case
>     if purpose not in messages.keys():
>         return None
> ```

should this not raise an error that is logged?
___
*[main.py, line 185 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-Mwf8Buj3CVvi8MzXfRT:-Mwf8Buj3CVvi8MzXfRU:baki6qn) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L185)):*
> ```Python
>                 }).json()
>         elif purpose == 'tar_notify':
> ```

can you add a comment to make it clear what is different / happening with `tar_notify`
___
*[main.py, line 977 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MwfAzyF1UZIQ0QZOCsn:-MwfAzyF1UZIQ0QZOCso:b7em0dv) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L977)):*
> ```Python
> 
>     Return:
>         If today.day is between 1-15: return 15
> ```

does this not return a datetime object and not a integer like the docstring says?

if it is just an integer of 1 or 15 it could just be:
` return 15 if today.day <= 15 else 1`
___
*[main.py, line 992 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MwfFb8S0td11KN7yTaX:-MwfFb8S0td11KN7yTaY:b-b6ffeu) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L992)):*
> ```Python
>     Function to turn modified epoch (returned by DNANexus)
>     into readable datetime format
> ```

input missing from doc string
___
*[main.py, line 1069 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MwfGDLC6WIek3oqNOHH:-MwfGDLC6WIek3oqNOHI:b-6uwxxu) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L1069)):*
> ```Python
>             find_projs_and_notify(archive_pickle, today)
> 
>     elif today.day > 1 and today.day < 15:
> ```

this can just be `if today.day < 15:` right, since we can't have negative days?

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 2 of 10 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[main.py, line 134 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-Mwf7UYs0flLPPbHNEp7:-MwgF31o7INDI0KdE8Mp:b-28ql1k) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L134)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should this not raise an error that is logged?
</blockquote></details>

thought about it but think it's hard to justify this as long as the function post_message_to_slack is defined correctly.  Removed.
___
*[main.py, line 185 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-Mwf8Buj3CVvi8MzXfRT:-MwgDNqdA9suszZbPoTJ:b-7tfmjp) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L185)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add a comment to make it clear what is different / happening with `tar_notify`
</blockquote></details>

added
___
*[main.py, line 977 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MwfAzyF1UZIQ0QZOCsn:-MwgEbn_-OFz3KAZnZE3:b-abe3uo) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L977)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this not return a datetime object and not a integer like the docstring says?

if it is just an integer of 1 or 15 it could just be:
` return 15 if today.day <= 15 else 1`
</blockquote></details>

it will return a datetime object, i added some comments to the function. 
___
*[main.py, line 992 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MwfFb8S0td11KN7yTaX:-MwgEy5g70XIph3iJUHb:bgxayje) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L992)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

input missing from doc string
</blockquote></details>

added input into comment
___
*[main.py, line 1069 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MwfGDLC6WIek3oqNOHH:-MwgF-BL52VwpIlbI_Zp:b-xrsrw0) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/52f69e6e3efffc9aada95582cf145d58b4335fc1/main.py#L1069)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this can just be `if today.day < 15:` right, since we can't have negative days?
</blockquote></details>

yes you're right. edited

**Comment by JasonLing95** [comment]
TODO
1. check for DataUsage to determine if project needs archiving or not?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r3, 1 of 2 files at r7, 3 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 15 at r8](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MxEluKdCLMhLCNd6ONa:-MxEluKdCLMhLCNd6ONb:b-q6610c) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/5e3a395879fcc23d0ea4c1678fcc000d0815f627/main.py#L15)):*
> ```Python
> import os
> import sys
> from xmlrpc.client import DateTime
> ```

you using this DateTime?
___
*[main.py, line 26 at r8](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MxElc1XBtxaHkocmEuJ:-MxElc1XBtxaHkocmEuK:b9jra3g) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/5e3a395879fcc23d0ea4c1678fcc000d0815f627/main.py#L26)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

>           File not in pull request at selected revision.
>         
>         Start a new discussion
>       
</details>
what is `member`?
___
*[main.py, line 210 at r8](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MxEkC0a-eoIQkdHAmL7:-MxEkC0a-eoIQkdHAmL8:b-e5qe3i) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/5e3a395879fcc23d0ea4c1678fcc000d0815f627/main.py#L210)):*
> ```Python
>             text_data = '\n'.join(data)
> 
>             if len(text_data) < 4000:
> ```

does this mean if there's a lot to display it will be sent as a text file instead of the links split by user? if its too long could we not just send more than one message?

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[main.py, line 15 at r8](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MxEluKdCLMhLCNd6ONa:-MxZ1De-AbnPTi6gxyov:bvimmoq) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/5e3a395879fcc23d0ea4c1678fcc000d0815f627/main.py#L15)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you using this DateTime?
</blockquote></details>

yes, just for function annotation for two functions: get_next_archiving_date and make_datetime_format
___
*[main.py, line 26 at r8](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MxElc1XBtxaHkocmEuJ:-MxZ1QOsDyQDaA2X2Won:bp2tmlb) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/5e3a395879fcc23d0ea4c1678fcc000d0815f627/main.py#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

>           File not in pull request at selected revision.
>         
>         Start a new discussion
>       
what is `member`?
</blockquote></details>

it's a folder on server which have members.py. It contains all our Slack ID and DNANexus username. Mainly for 003 projects separation in Slack notification
___
*[main.py, line 210 at r8](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MxEkC0a-eoIQkdHAmL7:-Mx_139C2OC7gWkM7CP8:b2ya32y) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/5e3a395879fcc23d0ea4c1678fcc000d0815f627/main.py#L210)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this mean if there's a lot to display it will be sent as a text file instead of the links split by user? if its too long could we not just send more than one message?
</blockquote></details>

edited to include a chunking function. Settled at chunk size of 40 because (trial-n-error) any number higher seems to get weird Slack notification truncation.

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[main.py, line 26 at r8](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-MxElc1XBtxaHkocmEuJ:-MxaFRSZA6y18tcwIHj2:b-7tfmjp) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/5e3a395879fcc23d0ea4c1678fcc000d0815f627/main.py#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add this to the requirments section of the readme
</blockquote></details>

added
___
*[main.py, line 309 at r9](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-Mx_CBm54x0TEwNvdQWb:-MxaXRmt7CbPGaYIw8J4:bk10408) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/55a25c555095cec02574ba097b38ece771eb70a0/main.py#L309)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will this break URLs if the split is in the middle? What is the structure of the message data and can we split it more robustly?
</blockquote></details>

we could do it like below as well. The data coming in is always a list of string (urls/project-id). We could either do it like chunker which cut a long list of values into list of 40 values each or like below, we cut the list based on their length so each list might have a different length. 



_Code snippet:_
```Python
text_data = []
start = 0
end = 1


for index in range(0, len(two_list) +1):
  chunk = two_list[start:end]
  
  if len('\n'.join(chunk)) < 7000:
    end = index

    if end == len(two_list):
      text_data.append(two_list[start:end])
  else:
    text_data.append(two_list[start:end])
    start = end - 1
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 309 at r9](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-Mx_CBm54x0TEwNvdQWb:-MxcpYCnEqqy9pBToSbM:b-t1b4g2) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/55a25c555095cec02574ba097b38ece771eb70a0/main.py#L309)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

we could do it like below as well. The data coming in is always a list of string (urls/project-id). We could either do it like chunker which cut a long list of values into list of 40 values each or like below, we cut the list based on their length so each list might have a different length. 
</blockquote></details>

what is `two_list`? If everything is already in a list and we want to turn it into a list of concatenated strings with a max length, something like this might work and be simpler:
```
message_list = []
curr_string = ""

for sub_str in two_list:
    if len(curr_string + sub_str) < 7000:
        curr_string += sub_str
    else:
        message_list.append(curr_string)
        curr_string = sub_str

```
or ignore me if that doesn't work for this

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[main.py, line 309 at r9](https://reviewable.io/reviews/eastgenomics/automated-archiving/3#-Mx_CBm54x0TEwNvdQWb:-Mxd7cHZA1dNqL8iw9XE:b-tmnkaa) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/55a25c555095cec02574ba097b38ece771eb70a0/main.py#L309)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is `two_list`? If everything is already in a list and we want to turn it into a list of concatenated strings with a max length, something like this might work and be simpler:
```
message_list = []
curr_string = ""

for sub_str in two_list:
    if len(curr_string + sub_str) < 7000:
        curr_string += sub_str
    else:
        message_list.append(curr_string)
        curr_string = sub_str

```
or ignore me if that doesn't work for this
</blockquote></details>

sorry, `two _list` is a list of 002_projects which i use to test the Slack message. I've changed the code, deleted chunker function and now it counts the length of '\n'.join(data), if longer than 7995 (trial-n-error, this number is the best, any higher seems to get truncation), it gets the previous endpoint data[start : end-1], kind of like a variable-size sliding window

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 5 files at r8, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
